# Generated by Django 4.1.3 on 2024-02-19 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=100, verbose_name='enter your first name')),
                ('Lastname', models.CharField(max_length=100, verbose_name='enter you last name')),
                ('contact', models.IntegerField(verbose_name='enter your number')),
                ('Email', models.EmailField(max_length=254, verbose_name='enter your email')),
            ],
        ),
    ]
