# Generated by Django 4.1.3 on 2024-07-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='enter your petname:')),
                ('pettype', models.CharField(max_length=100, verbose_name='enter like dog or cat or pig:')),
            ],
        ),
    ]
